In [1]:
import numpy as np 
import pandas as pd 

In [2]:
df = pd.read_csv('heart.csv')

In [3]:
df.sample(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
114   59    1   2       126   218    1        1      134      0      2.2   
281   35    1   1       122   192    0        1      174      0      0.0   
696   50    0   2       120   219    0        1      158      0      1.6   
101   57    1   2       150   126    1        1      173      0      0.2   
20    60    1   2       140   185    0        0      155      0      3.0   

     slope  ca  thal  target  
114      1   1     1       0  
281      2   0     2       1  
696      1   0     2       1  
101      2   1     3       1  
20       1   0     2       0

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [6]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [7]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\debsa\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [8]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [9]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.848780487804878
Accuracy of Decision Trees 0.9804878048780488


In [10]:
confusion_matrix(y_test,y_pred1)

array([[82, 23],
       [ 8, 92]], dtype=int64)

In [11]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix



0   1
0  82  23
1   8  92

In [12]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [13]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  82  23
1   8  92
--------------------------------------------------
Precision -  0.8
Recall -  0.92
F1 score -  0.8558139534883721


In [28]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
     0    1
0  101    4
1    0  100
--------------------------------------------------
Precision -  0.9615384615384616
Recall -  1.0
F1 score -  0.9803921568627451


In [30]:
precision_score(y_test,y_pred1,average=None)

array([0.91111111, 0.8       ])

In [32]:
precision_score(y_test,y_pred2,average=None)

array([1.        , 0.96153846])

In [34]:
recall_score(y_test,y_pred2,average=None)

array([0.96190476, 1.        ])