In [1]:
import numpy as np

In [3]:
arr1= np.array([1,2,3,4,5,6])
arr2= np.array([4,5,6,7,8,9])

In [5]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [7]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [9]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [19]:
arr2>3

array([ True,  True,  True,  True,  True,  True])

In [21]:
arr3= np.arange(6).reshape(2,3)
arr4= np.arange(6,12).reshape(3,2)

In [25]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

Dot operation👇

In [27]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [32]:
arr1.dot(arr2)

154

In [34]:
arr1.dot(arr3)

ValueError: shapes (6,) and (2,3) not aligned: 6 (dim 0) != 2 (dim 0)

In [36]:
arr4.max()

11

In [38]:
arr4.min()

6

In [40]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [42]:
arr4.min(axis=0) #column wise min

array([6, 7])

In [44]:
arr4.min(axis=1) #row wise min

array([ 6,  8, 10])

In [46]:
arr4.sum()

51

In [50]:
arr4.sum(axis=0)

array([24, 27])

In [52]:
arr4.mean()

8.5

In [54]:
arr4.mean(axis=1)

array([ 6.5,  8.5, 10.5])

In [56]:
arr4.std() #standard deviation

1.707825127659933

In [58]:
arr4.std(axis=0)

array([1.63299316, 1.63299316])

In [62]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [64]:
np.median(arr4)

8.5

In [66]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [68]:
arr4.ndim

2

In [70]:
arr4.ravel() #ndim -> 1 dim

array([ 6,  7,  8,  9, 10, 11])

In [72]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [74]:
arr5= np.arange(12,18).reshape(2,3)

In [76]:
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [78]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [84]:
np.hstack((arr3,arr5)) #horizontal stack 2 arrays

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [86]:
np.vstack((arr3,arr5)) #vertical stack 2 arrays

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [88]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [94]:
np.hsplit(arr3,3) #horizontal split an array (arr name,no. of sections)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [98]:
np.vsplit(arr3,2) #vertical split an array (arr name,no. of sections)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

Fancy Indexing👇

In [101]:
arr8= np.arange(24).reshape(6,4)

In [103]:
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [107]:
arr8[[0,2,4]] #extracts multiple rows (discontinous) #easily available in pandas

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])