In [2]:
import numpy as np

In [10]:
arr = np.random.randint(low=1, high=100, size=20).reshape(4,5)
arr

array([[32, 68,  8, 69, 14],
       [95, 94, 28,  3,  8],
       [76, 80, 99, 66, 95],
       [86, 77, 94, 32, 90]])

In [14]:
arr>50

array([[False,  True, False,  True, False],
       [ True,  True, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True]])

Indexing using boolean arrays

In [17]:
arr[arr>50]

array([68, 69, 95, 94, 76, 80, 99, 66, 95, 86, 77, 94, 90])

In [21]:
arr[(arr>50) & (arr%2 != 0)] 

array([69, 95, 99, 95, 77])

In [23]:
arr[(arr>50) & (arr%2 != 0)] = 0
arr

array([[32, 68,  8,  0, 14],
       [ 0, 94, 28,  3,  8],
       [76, 80,  0, 66,  0],
       [86,  0, 94, 32, 90]])

Graphs

In [28]:
x= np.linspace(-40,40,100) #100 numbers from -40 to 40 linearly spaced
x

array([-40.        , -39.19191919, -38.38383838, -37.57575758,
       -36.76767677, -35.95959596, -35.15151515, -34.34343434,
       -33.53535354, -32.72727273, -31.91919192, -31.11111111,
       -30.3030303 , -29.49494949, -28.68686869, -27.87878788,
       -27.07070707, -26.26262626, -25.45454545, -24.64646465,
       -23.83838384, -23.03030303, -22.22222222, -21.41414141,
       -20.60606061, -19.7979798 , -18.98989899, -18.18181818,
       -17.37373737, -16.56565657, -15.75757576, -14.94949495,
       -14.14141414, -13.33333333, -12.52525253, -11.71717172,
       -10.90909091, -10.1010101 ,  -9.29292929,  -8.48484848,
        -7.67676768,  -6.86868687,  -6.06060606,  -5.25252525,
        -4.44444444,  -3.63636364,  -2.82828283,  -2.02020202,
        -1.21212121,  -0.4040404 ,   0.4040404 ,   1.21212121,
         2.02020202,   2.82828283,   3.63636364,   4.44444444,
         5.25252525,   6.06060606,   6.86868687,   7.67676768,
         8.48484848,   9.29292929,  10.1010101 ,  10.90

In [30]:
x.size

100

In [32]:
y= np.sin(x)

In [34]:
y.size

100