In [6]:
import numpy as np

indexing and slicing

In [8]:
arr12 = np.arange(24)
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
arr12[2]

array([ 8,  9, 10, 11])

In [18]:
arr12[2,3]

11

In [20]:
arr12[:2] 

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [28]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [38]:
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [41]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [43]:
arr12[4:6,2:4]

array([[18, 19],
       [22, 23]])

iteration

In [46]:
arr12 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [50]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
