In [18]:
#creating numpy/n-d arrays
import numpy as np

In [22]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [24]:
type(arr1)

numpy.ndarray

In [26]:
arr2= np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr3= np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
arr4= np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
arr5= np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
arr6= np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr7= np.arange(5,16)
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
arr7= np.arange(5,16,2)
arr7

array([ 5,  7,  9, 11, 13, 15])

In [46]:
arr8= np.linspace(10,20,10)
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [48]:
arr9 = arr8.copy()
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [50]:
arr1

array([1, 2, 3, 4, 5])

In [52]:
arr1.shape

(5,)

In [54]:
arr2.shape

(2, 3)

In [56]:
arr10= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr10

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [58]:
arr10.shape

(2, 2, 2)

In [62]:
arr10.ndim

3

In [64]:
arr1.ndim

1

In [66]:
arr10.size

8

In [68]:
arr10.itemsize

4

In [70]:
arr9.dtype

dtype('float64')

In [72]:
arr10.dtype

dtype('int32')

In [74]:
arr10.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [88]:
lista= range(100)
arr11= np.arange(100)

In [80]:
import sys #sys -> systtem -> getsize of

In [82]:
print(sys.getsizeof(87)*len(lista)) #87 -> random b/w 0 - 99

2800


2800 bytes

In [90]:
print(arr11.itemsize*arr11.size)

400


400 bytes

In [93]:
import time

In [ ]:
x = range(100000)
y = range(100000,2000000)

start_time = time.time()

c = [x+y for x,y in zip(x,y)]

print(time.time() - start_time)

In [ ]:
a = np.arange(100000)
b = np.arange(100000,20000)

start_time = time.time()

c = a+b

print(time.time()-start_time)

array takes less time than list