Numpy Functions

In [3]:
import numpy as np

In [7]:
np.random.random()

0.2495632848904018

In [13]:
np.random.seed(1) #seed gives the same random value
np.random.random()

0.417022004702574

In [19]:
np.random.uniform(1,10) #random value b/w 1 and 10

3.7209931536865577

In [25]:
np.random.uniform(1,100,10) #10 random values b/w 1 and 100

array([87.76252608, 89.56605969,  9.41937693,  4.86642354, 17.81321154,
       87.93610784, 10.73633655, 42.68965488, 95.83106348, 53.78336321])

In [27]:
np.random.uniform(1,100,10).reshape(2,5)

array([[69.49583428, 32.23604747, 68.96359184, 83.62794152,  2.81053946],
       [75.26428718, 98.8972478 , 75.06839978, 28.76395521, 79.13865352]])

In [29]:
np.random.randint(1,10,15).reshape(3,5)

array([[9, 7, 4, 8, 8],
       [5, 6, 4, 7, 9],
       [1, 3, 8, 8, 8]])

In [33]:
a= np.random.randint(1,10,6)
a

array([2, 4, 1, 9, 7, 5])

In [35]:
np.max(a)

9

In [37]:
np.min(a)

1

In [39]:
np.argmax(a)

3

In [41]:
a[np.argmax(a)]

9

In [43]:
a[np.argmin(a)]

1

In [45]:
np.argmin(a)

2

In [47]:
a= np.random.randint(1,10,6)
a

array([6, 7, 3, 6, 8, 9])

In [50]:
a[a%2==1] = -1
a

array([ 6, -1, -1,  6,  8, -1])

np.where -> Where(condition,true,false)

In [57]:
a= np.random.randint(1,50,6)
a

array([19, 33, 14, 11, 24, 18])

In [59]:
np.where(a%2==1, -1, a)

array([-1, -1, 14, -1, 24, 18])

In [61]:
a

array([19, 33, 14, 11, 24, 18])

In [65]:
b= np.where(a%2==1, -1, a)
b

array([-1, -1, 14, -1, 24, 18])

In [69]:
a= np.random.randint(1,50,10)
a

array([13,  2, 31, 42, 25, 19, 34,  3, 45, 29])

In [73]:
a= np.sort(a)
a

array([ 2,  3, 13, 19, 25, 29, 31, 34, 42, 45])

In [75]:
np.percentile(a,25)

14.5

In [77]:
np.percentile(a,99.8)

44.946